name: CI and Development Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
  RunLinters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 19

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run tsc
        run: npm run tsc

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

  DeployPRPreview:
    name: Deploy PR Preview to Vercel
    runs-on: ubuntu-latest
    needs:
      - RunLinters

    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      - uses: aaimio/vercel-preview-url-action@v2.0.0
        id: vercel_preview_url
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: garrettjoecox/pr-section@main
        if: ${{ github.event_name == 'pull_request' }}
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          section-name: 'pr-preview-url'
          section-value: '[Preview URL](${{ steps.vercel_preview_url.outputs.vercel_preview_url }}'
